using BibleTalkAI.OpenAI.Threads.Models;
using BibleTalkAI.OpenAI.Tools.Models;
using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace BibleTalkAI.OpenAI.Threads.Json;

[JsonSourceGenerationOptions(
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
// system types
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(bool))]
// collections
[JsonSerializable(typeof(ImmutableDictionary<string, string?>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(ImmutableArray<string>))]
// api types
[JsonSerializable(typeof(Attachment))]
[JsonSerializable(typeof(Attachment?))]
[JsonSerializable(typeof(Tool))]
[JsonSerializable(typeof(Tool?))]
[JsonSerializable(typeof(ToolResource))]
[JsonSerializable(typeof(ToolResource?))]
[JsonSerializable(typeof(Function))]
[JsonSerializable(typeof(Function?))]
[JsonSerializable(typeof(FunctionParameter))]
[JsonSerializable(typeof(FunctionParameter?))]
[JsonSerializable(typeof(Models.Thread))]
[JsonSerializable(typeof(Models.Thread?))]
[JsonSerializable(typeof(ThreadCreate))]
[JsonSerializable(typeof(ThreadCreate?))]
[JsonSerializable(typeof(MessageCreate))]
[JsonSerializable(typeof(MessageCreate?))]
[JsonSerializable(typeof(ThreadModify))]
[JsonSerializable(typeof(ThreadModify?))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(Message?))]
[JsonSerializable(typeof(MessageContent))]
[JsonSerializable(typeof(MessageContent?))]
[JsonSerializable(typeof(MessageContentText))]
[JsonSerializable(typeof(MessageContentText?))]
[JsonSerializable(typeof(MessageModify))]
[JsonSerializable(typeof(MessageModify?))]
[JsonSerializable(typeof(MessageList))]
[JsonSerializable(typeof(MessageList?))]
[JsonSerializable(typeof(Run))]
[JsonSerializable(typeof(Run?))]
[JsonSerializable(typeof(RunError))]
[JsonSerializable(typeof(RunError?))]
[JsonSerializable(typeof(RunRequiredAction))]
[JsonSerializable(typeof(RunRequiredAction?))]
[JsonSerializable(typeof(RunSubmitToolOutputs))]
[JsonSerializable(typeof(RunSubmitToolOutputs?))]
[JsonSerializable(typeof(RunToolCall))]
[JsonSerializable(typeof(RunToolCall?))]
[JsonSerializable(typeof(RunToolCallFunction))]
[JsonSerializable(typeof(RunToolCallFunction?))]
[JsonSerializable(typeof(RunCreate))]
[JsonSerializable(typeof(RunCreate?))]
[JsonSerializable(typeof(RunModify))]
[JsonSerializable(typeof(RunModify?))]
[JsonSerializable(typeof(RunList))]
[JsonSerializable(typeof(RunList?))]
[JsonSerializable(typeof(SubmitToolOutputs))]
[JsonSerializable(typeof(SubmitToolOutputs?))]
[JsonSerializable(typeof(ToolOutput))]
[JsonSerializable(typeof(ToolOutput?))]
[JsonSerializable(typeof(ThreadAndRunCreate))]
[JsonSerializable(typeof(ThreadAndRunCreate?))]
[JsonSerializable(typeof(RunStep))]
[JsonSerializable(typeof(RunStep?))]
[JsonSerializable(typeof(RunStepDetails))]
[JsonSerializable(typeof(RunStepDetails?))]
[JsonSerializable(typeof(MessageCreation))]
[JsonSerializable(typeof(MessageCreation?))]
[JsonSerializable(typeof(RunStepList))]
[JsonSerializable(typeof(RunStepList?))]
// collections
[JsonSerializable(typeof(ImmutableArray<Attachment>))]
[JsonSerializable(typeof(ImmutableArray<Attachment>?))]
[JsonSerializable(typeof(ImmutableArray<Tool>))]
[JsonSerializable(typeof(ImmutableArray<Tool>?))]
[JsonSerializable(typeof(ImmutableArray<FunctionParameter>))]
[JsonSerializable(typeof(ImmutableArray<FunctionParameter>?))]
[JsonSerializable(typeof(ImmutableArray<MessageCreate>))]
[JsonSerializable(typeof(ImmutableArray<MessageCreate>?))]
[JsonSerializable(typeof(ImmutableArray<MessageContent>))]
[JsonSerializable(typeof(ImmutableArray<MessageContent>?))]
[JsonSerializable(typeof(ImmutableArray<Message>))]
[JsonSerializable(typeof(ImmutableArray<Message>?))]
[JsonSerializable(typeof(ImmutableArray<RunToolCall>))]
[JsonSerializable(typeof(ImmutableArray<RunToolCall>?))]
[JsonSerializable(typeof(ImmutableArray<Run>))]
[JsonSerializable(typeof(ImmutableArray<Run>?))]
[JsonSerializable(typeof(ImmutableArray<ToolOutput>))]
[JsonSerializable(typeof(ImmutableArray<ToolOutput>?))]
[JsonSerializable(typeof(ImmutableArray<RunStep>))]
[JsonSerializable(typeof(ImmutableArray<RunStep>?))]
internal partial class GeneratedJsonSerializerContext
    : JsonSerializerContext
{
}
